/*
 * $Id: arms_xml_tag.c 10126 2008-08-07 04:03:45Z m-oki $
 *
 * This file is auto generated from XML_TAG.def
 * DO NOT EDIT THIS FILE DIRECTRY.
 *
 */
#include <stdio.h>
#include <stdlib.h>
#include <arms_xml_tag.h>

const char *
str_tag(enum arms_msg_tags id)
{
	const char *str;

	switch (id) {
	case ARMS_TAG_MSG:
		str = "arms-message";
		break;
	case ARMS_TAG_REQ:
		str = "arms-request";
		break;
	case ARMS_TAG_RES:
		str = "arms-response";
		break;
	case ARMS_TAG_DISTID:
		str = "distribution-id";
		break;
	case ARMS_TAG_DESC:
		str = "description";
		break;
	case ARMS_TAG_RCODE:
		str = "result-code";
		break;
	case ARMS_TAG_RDESC:
		str = "description";
		break;
	case ARMS_TAG_EREASON:
		str = "error-reason";
		break;
	case ARMS_TAG_RSSOL_REQ:
		str = "rs-solicitation-request";
		break;
	case ARMS_TAG_TRIGGER:
		str = "trigger";
		break;
	case ARMS_TAG_HWINFO:
		str = "hardware-info";
		break;
	case ARMS_TAG_FWINFO:
		str = "firmware-info";
		break;
	case ARMS_TAG_PROPOSAL:
		str = "proposal-for-sa";
		break;
	case ARMS_TAG_PUSH_PORT:
		str = "push-port";
		break;
	case ARMS_TAG_PUSH_TIMEOUT:
		str = "push-timeout";
		break;
	case ARMS_TAG_RSSOL_RES:
		str = "rs-solicitation-response";
		break;
	case ARMS_TAG_CONFSOL_RES:
		str = "config-solicitation-response";
		break;
	case ARMS_TAG_LLTIMEOUT:
		str = "ll-timeout";
		break;
	case ARMS_TAG_RS_RETRY_MAX:
		str = "rs-retry-max";
		break;
	case ARMS_TAG_RS_RETRY_INT:
		str = "rs-retry-int";
		break;
	case ARMS_TAG_LIFETIME:
		str = "lifetime";
		break;
	case ARMS_TAG_HBEAT_INFO:
		str = "heartbeat-info";
		break;
	case ARMS_TAG_HOST:
		str = "host";
		break;
	case ARMS_TAG_PORT:
		str = "port";
		break;
	case ARMS_TAG_PASSPHRASE:
		str = "passphrase";
		break;
	case ARMS_TAG_INTERVAL:
		str = "interval";
		break;
	case ARMS_TAG_ALGORITHM:
		str = "algorithm";
		break;
	case ARMS_TAG_HEALTH_URL:
		str = "health-url";
		break;
	case ARMS_TAG_HEALTH_INT:
		str = "health-interval";
		break;
	case ARMS_TAG_POLL_URL:
		str = "poll-url";
		break;
	case ARMS_TAG_POLL_INT:
		str = "poll-interval";
		break;
	case ARMS_TAG_RS_INFO:
		str = "rs-info";
		break;
	case ARMS_TAG_RS_KEY:
		str = "rs-preshared-key";
		break;
	case ARMS_TAG_URL:
		str = "url";
		break;
	case ARMS_TAG_MDCONF:
		str = "md-config";
		break;
	case ARMS_TAG_MODULE:
		str = "module";
		break;
	case ARMS_TAG_MOD_ID:
		str = "id";
		break;
	case ARMS_TAG_MOD_SUBID:
		str = "sub-id";
		break;
	case ARMS_TAG_PUSH_EP:
		str = "push-endpoint";
		break;
	case ARMS_TAG_PUSH_ADDRESS:
		str = "rs-push-server-address";
		break;
	case ARMS_TAG_PULL_SERVER_URL:
		str = "rs-pull-server-url";
		break;
	case ARMS_TAG_SA_CERTIFICATE:
		str = "sa-certificate";
		break;
	case ARMS_TAG_SA_PRIVATE_KEY:
		str = "sa-private-key";
		break;
	case ARMS_TAG_SA_ADDR:
		str = "sa-address";
		break;
	case ARMS_TAG_SA_ADDR_RES:
		str = "detected-sa-address";
		break;
	case ARMS_TAG_RS_ADDR:
		str = "rs-address";
		break;
	case ARMS_TAG_RS_ADDR_RES:
		str = "detected-rs-address";
		break;
	case ARMS_TAG_PUSH_RDY_REQ:
		str = "push-ready-request";
		break;
	case ARMS_TAG_PUSH_RDY_RES:
		str = "push-ready-response";
		break;
	case ARMS_TAG_UPDATE_INT:
		str = "update-interval";
		break;
	case ARMS_TAG_GETTRANS_REQ:
		str = "get-transaction-request";
		break;
	case ARMS_TAG_GETTRANS_RES:
		str = "get-transaction-response";
		break;
	case ARMS_TAG_TRANSACTION_ID:
		str = "transaction-id";
		break;
	case ARMS_TAG_TRANSACTION_ID1:
		str = "transaction-id";
		break;
	case ARMS_TAG_TRANSACTION_ID2:
		str = "transaction-id";
		break;
	case ARMS_TAG_TRANSACTION_ID3:
		str = "transaction-id";
		break;
	case ARMS_TAG_MDRESULT:
		str = "md-result";
		break;
	case ARMS_TAG_METHOD:
		str = "method";
		break;
	case ARMS_TAG_STORAGE:
		str = "storage";
		break;
	case ARMS_TAG_MDERROR:
		str = "md-error";
		break;
	case ARMS_TAG_ERR_DETAIL:
		str = "error-detail";
		break;
	case ARMS_TAG_TYPE:
		str = "type";
		break;
	case ARMS_TAG_CONFIGURE_SREQ:
		str = "configure-start-request";
		break;
	case ARMS_TAG_CONFIGURE_SRES:
		str = "configure-start-response";
		break;
	case ARMS_TAG_CONFIGURE_DREQ:
		str = "configure-done-request";
		break;
	case ARMS_TAG_CONFIGURE_DRES:
		str = "configure-done-response";
		break;
	case ARMS_TAG_READSTORAGE_SREQ:
		str = "read-storage-start-request";
		break;
	case ARMS_TAG_READSTORAGE_SRES:
		str = "read-storage-start-response";
		break;
	case ARMS_TAG_READSTORAGE_DREQ:
		str = "read-storage-done-request";
		break;
	case ARMS_TAG_READSTORAGE_DRES:
		str = "read-storage-done-response";
		break;
	case ARMS_TAG_READSTATUS_SREQ:
		str = "read-status-start-request";
		break;
	case ARMS_TAG_READSTATUS_SRES:
		str = "read-status-start-response";
		break;
	case ARMS_TAG_READSTATUS_DREQ:
		str = "read-status-done-request";
		break;
	case ARMS_TAG_READSTATUS_DRES:
		str = "read-status-done-response";
		break;
	case ARMS_TAG_MDSTATUS:
		str = "md-status";
		break;
	case ARMS_TAG_STATUS_REQ:
		str = "status-request";
		break;
	case ARMS_TAG_STATUS_REP:
		str = "status-report";
		break;
	case ARMS_TAG_REBOOT_REQ:
		str = "reboot-request";
		break;
	case ARMS_TAG_REBOOT_RES:
		str = "reboot-response";
		break;
	case ARMS_TAG_CHK_TRANSACTION_RES:
		str = "check-transaction-response";
		break;
	case ARMS_TAG_DUMP_DEBUG_REQ:
		str = "dump-debug-request";
		break;
	case ARMS_TAG_DUMP_DEBUG_RES:
		str = "dump-debug-response";
		break;
	case ARMS_TAG_PING_SREQ:
		str = "ping-start-request";
		break;
	case ARMS_TAG_PING_SRES:
		str = "ping-start-response";
		break;
	case ARMS_TAG_PING_DREQ:
		str = "ping-done-request";
		break;
	case ARMS_TAG_PING_DRES:
		str = "ping-done-response";
		break;
	case ARMS_TAG_ADDR:
		str = "address";
		break;
	case ARMS_TAG_CNT:
		str = "count";
		break;
	case ARMS_TAG_SIZ:
		str = "size";
		break;
	case ARMS_TAG_SUCCESS:
		str = "success";
		break;
	case ARMS_TAG_FAIL:
		str = "failure";
		break;
	case ARMS_TAG_TRACEROUTE_SREQ:
		str = "traceroute-start-request";
		break;
	case ARMS_TAG_TRACEROUTE_SRES:
		str = "traceroute-start-response";
		break;
	case ARMS_TAG_TRACEROUTE_DREQ:
		str = "traceroute-done-request";
		break;
	case ARMS_TAG_TRACEROUTE_DRES:
		str = "traceroute-done-response";
		break;
	case ARMS_TAG_MAX_HOP:
		str = "max-hop";
		break;
	case ARMS_TAG_READMODLIST_REQ:
		str = "read-module-list-request";
		break;
	case ARMS_TAG_READMODLIST_RES:
		str = "read-module-list-response";
		break;
	case ARMS_TAG_PULLCONFIG_REQ:
		str = "pull-config-request";
		break;
	case ARMS_TAG_PULLCONFIG_RES:
		str = "pull-config-response";
		break;
	case ARMS_TAG_CLEARSTATUS_SREQ:
		str = "clear-status-start-request";
		break;
	case ARMS_TAG_CLEARSTATUS_SRES:
		str = "clear-status-start-response";
		break;
	case ARMS_TAG_CLEARSTATUS_DREQ:
		str = "clear-status-done-request";
		break;
	case ARMS_TAG_CLEARSTATUS_DRES:
		str = "clear-status-done-response";
		break;
	case ARMS_TAG_MDCOMMAND_REQ:
		str = "md-command-request";
		break;
	case ARMS_TAG_MDCOMMAND_RES:
		str = "md-command-response";
		break;
	case ARMS_TAG_MDCOMMAND:
		str = "md-command";
		break;
	case ARMS_TAG_RESULT_URL:
		str = "result-url";
		break;
	case ARMS_TAG_METHOD_QUERY_RES:
		str = "push-method-query-response";
		break;
	case ARMS_TAG_PUSH_METHOD:
		str = "push-method";
		break;
	case ARMS_TAG_TUNNEL_URL:
		str = "https-tunnel-url";
		break;
	case ARMS_TAG_ECHO_INTERVAL:
		str = "https-tunnel-echo-interval";
		break;
	case ARMS_TAG_CONFIRM_SREQ:
		str = "push-confirmation-start-request";
		break;
	case ARMS_TAG_CONFIRM_SRES:
		str = "push-confirmation-start-response";
		break;
	case ARMS_TAG_CONFIRM_DREQ:
		str = "push-confirmation-done-request";
		break;
	case ARMS_TAG_CONFIRM_DRES:
		str = "push-confirmation-done-response";
		break;
	default:
		str = "unknown_xml_tag";
		break;
	}
	return str;
}
